### ISSUE TITLE
How can I obtain the HOG-LDA similarity matrix by myself?

### ISSUE THREAD

**Issue by zaie** [asanakoy/cliquecnn#1]
Hello, this question is related to the Initialization step of your paper. I suppose the details are as following:
1. Get the bounding box using the method mentioned in paper (A discriminatively trained, multiscale, deformable part model).
2. Resize these bounding boxes to the same size (maybe 227*227 as indicated by prototxt files), so that the HOG-LDA descriptors are with the same dimension and the s_ij can be calculated as described in 2.1 of your paper.
Am I right? If I'm right, how can I ensure that the bounding boxes I got are the same with yours? If I'm wrong, please tell me the right details initialization.
Thanks!

**Comment by asanakoy** [comment]
Everything is right.
I have committed bounding boxes for OlympicSports: 86ed8b8860db4b2d8da42a4159153b5f9c0b8995.
